#!/bin/sh

set -e
set -x

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends default-jre-headless daemontools
apt-get clean
adduser --system --home /srv/minecraft --group --quiet minecraft
