#!/bin/sh

set -e
set -x

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends default-jre-headless
apt-get clean
adduser --system --home /srv/minecraft --uid 900 --group --quiet minecraft
